# idx: (decision, vertical/reason, zi_employees, verify_flag)
R = {
14:("T","Security Integrator (multi-line)",19,""),
17:("T","Security Integrator (multi-line)",23,"Verify"),
18:("N","Unclear / not buy-box",8,""),
26:("N","No ZoomInfo match - unverifiable",None,""),
37:("A","Low-voltage / cabling",8,""),
39:("N","IT services",32,""),
66:("T","Security Integrator (multi-line)",31,""),
71:("N","Telecom / IT (same co. as Phonetel)",14,""),
73:("T","Security Integrator (multi-line)",7,""),
74:("N","Not buy-box (membership org)",5,""),
76:("N","Telecom",18,""),
91:("N","Guard services",55,""),
96:("A","Managed wireless / IT w/ security",21,""),
104:("T","Alarm & Monitoring",17,""),
109:("A","Construction - adjacent",35,"Verify"),
111:("N","IT services",41,""),
115:("T","Security Integrator (multi-line)",10,""),
117:("T","Security Integrator (multi-line)",14,""),
125:("N","Defunct; acquired by Mobile Communications America",125,""),
127:("D","Duplicate of Defender One Security (MD)",34,""),
128:("T","Alarm & Monitoring",20,""),
130:("N","Management consulting",29,""),
135:("N","Software",26,""),
151:("A","Low-voltage / cabling",19,""),
153:("N","Unclear / not buy-box",15,""),
163:("N","Out of footprint (Riga, Latvia)",41,""),
168:("T","Doors, Gates & Entrances",27,"Verify"),
171:("N","IT services",17,""),
173:("A","Building automation / controls",153,""),
177:("A","Low-voltage / communications",24,""),
179:("N","No ZoomInfo match - unverifiable",None,""),
191:("N","Finance / lending",26,""),
194:("T","Alarm & Monitoring",12,"Verify - residential lean"),
197:("N","Two-way radio / telecom",95,""),
204:("T","Security Integrator (multi-line)",19,""),
206:("T","Security Integrator (multi-line)",29,""),
207:("T","Security Integrator (multi-line)",72,""),
221:("T","Security Integrator (multi-line)",12,""),
222:("N","Wireless / telecom infrastructure",101,""),
229:("T","Security Integrator (multi-line)",92,""),
239:("A","Low-voltage / cabling",24,""),
241:("T","Alarm & Monitoring",34,""),
246:("T","Fire & Life Safety",94,""),
250:("N","Manufacturer (building materials)",95,""),
252:("N","Out of footprint (Davenport, IA); electrical",82,""),
253:("N","IT services",35,""),
255:("A","Hardware / door distributor",25,""),
256:("T","Security Integrator (multi-line)",15,""),
264:("N","No ZoomInfo match - unverifiable",None,""),
265:("N","No ZoomInfo match - unverifiable",None,""),
266:("N","IT services",18,""),
267:("A","Engineering / controls integrator",40,""),
271:("D","Duplicate of ENE Systems",165,""),
279:("A","Low-voltage / IT",19,""),
289:("T","Fire & Life Safety",17,"Verify"),
291:("T","Security Integrator (multi-line)",13,"Verify"),
294:("T","Security Integrator (multi-line)",8,"Verify"),
296:("N","Electrical contractor",16,""),
303:("N","No ZoomInfo match - unverifiable",None,""),
305:("T","Security Integrator (multi-line)",23,""),
307:("N","Construction / electrical",10,""),
309:("N","No ZoomInfo match - unverifiable",None,""),
314:("N","Owned by Allied Universal",21,""),
328:("N","IT services",16,""),
329:("T","Security Integrator (multi-line)",19,"Verify"),
331:("A","Controls",12,""),
339:("N","IT services",12,""),
340:("N","IT services",15,""),
344:("T","Video Surveillance",59,""),
347:("N","IT services",11,""),
354:("N","Electrical contractor",6,""),
387:("T","Locksmith & Door Hardware",7,""),
392:("T","Security Integrator (multi-line)",19,""),
394:("N","Defunct",23,""),
405:("A","Building systems",31,""),
433:("N","Construction contractor",7,""),
438:("T","Security Integrator (multi-line)",11,""),
457:("T","Doors, Gates & Entrances",8,""),
460:("N","Training / consulting; domain mismatch",60,""),
474:("N","No ZoomInfo match - unverifiable",None,""),
476:("T","Security Integrator (multi-line)",8,""),
480:("N","Unclear / not buy-box",6,""),
487:("T","Security Integrator (multi-line)",15,""),
488:("T","Security Integrator (multi-line)",6,""),
493:("N","Holding company",41,""),
495:("N","No ZoomInfo match - unverifiable",None,""),
513:("T","Security Integrator (multi-line)",7,"Verify"),
516:("T","Alarm & Monitoring",10,""),
524:("T","Security Integrator (multi-line)",5,""),
526:("N","Electrical contractor",15,""),
531:("N","Management consulting",3,""),
544:("N","Owned by DW Security",25,""),
559:("D","Duplicate of Main Line Security Solutions",None,""),
562:("T","Security Integrator (multi-line)",65,""),
572:("T","Security Integrator (multi-line)",22,"Verify"),
578:("T","Security Integrator (multi-line)",8,""),
582:("T","Security Integrator (multi-line)",22,""),
583:("T","Security Integrator (multi-line)",14,""),
588:("T","Alarm & Monitoring",8,"Verify"),
603:("N","Not a security operator (media)",8,""),
615:("T","Security Integrator (multi-line)",102,""),
622:("D","Duplicate of IronWatch Security",None,""),
623:("T","Security Integrator (multi-line)",19,""),
627:("T","Security Integrator (multi-line)",46,""),
633:("T","Alarm & Monitoring",29,""),
635:("N","Out of footprint (Grand Junction, CO)",7,""),
}
