# idx: (decision, vertical_or_reason)
# decisions: T=target, A=adjacent, N=non-target, U=uncertain (ZoomInfo check), D=duplicate
S = {
0:("T","Locksmith & Door Hardware"),1:("T","Doors, Gates & Entrances"),2:("T","Alarm & Monitoring"),
3:("T","Security Integrator (multi-line)"),4:("T","Alarm & Monitoring"),5:("T","Alarm & Monitoring"),
6:("T","Locksmith & Door Hardware"),7:("T","Locksmith & Door Hardware"),8:("T","Locksmith & Door Hardware"),
9:("T","Alarm & Monitoring"),10:("T","Locksmith & Door Hardware"),11:("T","Alarm & Monitoring"),
12:("T","Alarm & Monitoring"),13:("N","AV / home theater"),14:("U",""),15:("N","Electrical contractor"),
16:("T","Alarm & Monitoring"),17:("U",""),18:("U",""),19:("T","Locksmith & Door Hardware"),
20:("T","Fire & Life Safety"),21:("T","Locksmith & Door Hardware"),22:("N","Telecom / voice"),
23:("T","Alarm & Monitoring"),24:("T","Locksmith & Door Hardware"),25:("T","Locksmith & Door Hardware"),
26:("U",""),27:("T","Locksmith & Door Hardware"),28:("T","Security Integrator (multi-line)"),
29:("D","Duplicate of Command Corporation"),30:("T","Security Integrator (multi-line)"),
31:("T","Alarm & Monitoring"),32:("T","Locksmith & Door Hardware"),33:("T","Locksmith & Door Hardware"),
34:("T","Locksmith & Door Hardware"),35:("T","Alarm & Monitoring"),36:("N","Residential home automation"),
37:("U",""),38:("T","Alarm & Monitoring"),39:("U",""),40:("T","Security Integrator (multi-line)"),
41:("N","Everon - national strategic (ex-ADT Commercial)"),42:("T","Fire & Life Safety"),
43:("T","Doors, Gates & Entrances"),44:("T","Alarm & Monitoring"),45:("T","Fire & Life Safety"),
46:("T","Fire & Life Safety"),47:("T","Fire & Life Safety"),48:("A","Electrical contractor w/ security division"),
49:("T","Locksmith & Door Hardware"),50:("N","Electrical contractor"),51:("T","Locksmith & Door Hardware"),
52:("T","Fire & Life Safety"),53:("N","Manufacturer"),54:("N","Manufacturer"),55:("N","Manufacturer"),
56:("N","Manufacturer"),57:("N","Manufacturer"),58:("N","Manufacturer"),59:("N","Manufacturer"),
60:("N","Electrical contractor"),61:("T","Alarm & Monitoring"),62:("T","Locksmith & Door Hardware"),
63:("T","Locksmith & Door Hardware"),64:("T","Alarm & Monitoring"),65:("T","Security Integrator (multi-line)"),
66:("U",""),67:("T","Locksmith & Door Hardware"),68:("N","Manufacturer (lock pinning kits)"),
69:("N","AV / media services"),70:("T","Locksmith & Door Hardware"),71:("U",""),72:("T","Alarm & Monitoring"),
73:("U",""),74:("U",""),75:("N","PE-owned (Sciens)"),76:("U",""),77:("T","Alarm & Monitoring"),
78:("T","Security Integrator (multi-line)"),79:("T","Alarm & Monitoring"),80:("T","Alarm & Monitoring"),
81:("T","Alarm & Monitoring"),82:("T","Alarm & Monitoring"),83:("T","Alarm & Monitoring"),
84:("T","Fire & Life Safety"),85:("T","Security Integrator (multi-line)"),86:("T","Locksmith & Door Hardware"),
87:("N","Electrical contractor"),88:("T","Locksmith & Door Hardware"),89:("T","Locksmith & Door Hardware"),
90:("N","Telecom"),91:("U",""),92:("T","Alarm & Monitoring"),93:("N","Guard services"),
94:("T","Locksmith & Door Hardware"),95:("T","Alarm & Monitoring"),96:("U",""),97:("T","Fire & Life Safety"),
98:("N","Residential alarm"),99:("T","Security Integrator (multi-line)"),100:("N","Consulting / media"),
101:("T","Alarm & Monitoring"),102:("N","Residential AV"),103:("N","PE-owned (Pye-Barker)"),104:("U",""),
105:("T","Alarm & Monitoring"),106:("T","Security Integrator (multi-line)"),107:("T","Security Integrator (multi-line)"),
108:("T","Locksmith & Door Hardware"),109:("U",""),110:("N","Electrical contractor"),111:("U",""),
112:("T","Security Integrator (multi-line)"),113:("N","PE-owned (Pye-Barker)"),114:("T","Security Integrator (multi-line)"),
115:("U",""),116:("T","Security Integrator (multi-line)"),117:("U",""),118:("T","Locksmith & Door Hardware"),
119:("N","Electrical contractor"),120:("T","Security Integrator (multi-line)"),121:("T","Locksmith & Door Hardware"),
122:("T","Locksmith & Door Hardware"),123:("N","Guard services"),124:("N","Guard services"),125:("U",""),
126:("T","Locksmith & Door Hardware"),127:("U",""),128:("U",""),129:("N","Guard services"),130:("U",""),
131:("N","Manufacturer"),132:("N","No real web presence"),133:("N","IT services"),
134:("T","Security Integrator (multi-line)"),135:("U",""),136:("N","Mortgage lender"),137:("N","Unclear / not buy-box"),
138:("N","AV / building services"),139:("N","Guard services"),140:("N","Consulting"),141:("N","Consulting"),
142:("T","Doors, Gates & Entrances"),143:("T","Alarm & Monitoring"),144:("N","Telecom / association"),
145:("N","Consulting"),146:("N","AV integrator"),147:("T","Alarm & Monitoring"),148:("N","Software"),
149:("N","Advisory"),150:("N","Electrical contractor"),151:("U",""),152:("T","Fire & Life Safety"),153:("U",""),
154:("T","Security Integrator (multi-line)"),155:("T","Alarm & Monitoring"),156:("N","Manufacturer"),
157:("N","Consulting"),158:("N","Electrical contractor"),159:("T","Alarm & Monitoring"),160:("N","Software"),
161:("N","Software"),162:("N","Manufacturer"),163:("U",""),164:("T","Alarm & Monitoring"),
165:("A","Building controls / HVAC"),166:("T","Alarm & Monitoring"),167:("T","Security Integrator (multi-line)"),
168:("U",""),169:("T","Alarm & Monitoring"),170:("N","Investment bank"),171:("U",""),172:("N","IT reseller"),
173:("U",""),174:("N","Software"),175:("N","Guard / investigations"),176:("N","Electrical contractor"),
177:("U",""),178:("N","Investigations"),179:("U",""),180:("A","Door hardware distributor"),
181:("N","Consulting"),182:("A","Building automation"),183:("N","SaaS / IoT platform"),
184:("T","Security Integrator (multi-line)"),185:("N","Association domain (afaa-ne.org) - not a company site"),
186:("T","Fire & Life Safety"),187:("T","Fire & Life Safety"),188:("N","Insurer"),189:("N","Software"),
190:("N","Advisor"),191:("U",""),192:("T","Locksmith & Door Hardware"),193:("T","Locksmith & Door Hardware"),
194:("U",""),195:("T","Locksmith & Door Hardware"),196:("T","Alarm & Monitoring"),197:("U",""),
198:("T","Locksmith & Door Hardware"),199:("A","Low-voltage / network cabling"),200:("T","Locksmith & Door Hardware"),
201:("N","Guard services"),202:("T","Access Control & Intercom"),203:("N","Above buy-box"),204:("U",""),
205:("N","Guard services"),206:("U",""),207:("U",""),208:("N","Guard services"),
209:("A","Security products distributor"),210:("T","Fire & Life Safety"),211:("T","Fire & Life Safety"),
212:("N","Consulting"),213:("N","PE platform (Sciens)"),214:("T","Alarm & Monitoring"),
215:("N","PE-owned (Pavion)"),216:("N","Media"),217:("T","Security Integrator (multi-line)"),
218:("T","Fire & Life Safety"),219:("N","IT services"),220:("N","Telecom"),221:("U",""),222:("U",""),
223:("N","Software"),224:("N","Guard / consulting"),225:("N","IT services"),226:("N","Software"),
227:("N","Consulting"),228:("N","Manufacturer"),229:("U",""),230:("N","Software"),231:("N","Training"),
232:("N","Software / mass notification"),233:("N","PE-owned (Sciens)"),234:("T","Alarm & Monitoring"),
235:("T","Alarm & Monitoring"),236:("N","SaaS"),237:("T","Alarm & Monitoring"),238:("N","Consulting"),
239:("U",""),240:("T","Security Integrator (multi-line)"),241:("U",""),242:("T","Locksmith & Door Hardware"),
243:("A","Low-voltage / cabling w/ security"),244:("T","Fire & Life Safety"),245:("N","Unclear / not buy-box"),
246:("U",""),247:("T","Locksmith & Door Hardware"),248:("T","Security Integrator (multi-line)"),
249:("T","Alarm & Monitoring"),250:("U",""),251:("T","Video Surveillance"),252:("U",""),253:("U",""),
254:("T","Locksmith & Door Hardware"),255:("U",""),256:("U",""),257:("T","Fire & Life Safety"),
258:("T","Security Integrator (multi-line)"),259:("T","Security Integrator (multi-line)"),
260:("N","Association"),261:("T","Alarm & Monitoring"),262:("T","Alarm & Monitoring"),
263:("T","Video Surveillance"),264:("U",""),265:("U",""),266:("U",""),267:("U",""),
268:("T","Security Integrator (multi-line)"),269:("N","PE-owned (Pye-Barker)"),270:("T","Fire & Life Safety"),
271:("U",""),272:("N","Manufacturer"),273:("T","Alarm & Monitoring"),274:("T","Locksmith & Door Hardware"),
275:("T","Fire & Life Safety"),276:("T","Security Integrator (multi-line)"),277:("T","Fire & Life Safety"),
278:("N","Software"),279:("U",""),280:("T","Alarm & Monitoring"),281:("A","Lock / hardware distributor"),
282:("T","Alarm & Monitoring"),283:("T","Alarm & Monitoring"),284:("T","Fire & Life Safety"),
285:("T","Locksmith & Door Hardware"),286:("N","Security consulting"),287:("T","Security Integrator (multi-line)"),
288:("T","Fire & Life Safety"),289:("U",""),290:("N","Media / events"),291:("U",""),
292:("T","Security Integrator (multi-line)"),293:("N","Manufacturer (gas detection)"),294:("U",""),
295:("T","Alarm & Monitoring"),296:("U",""),297:("T","Security Integrator (multi-line)"),
298:("T","Security Integrator (multi-line)"),299:("T","Security Integrator (multi-line)"),
300:("T","Fire & Life Safety"),301:("N","Roofing manufacturer"),302:("N","Electrical contractor"),
303:("U",""),304:("N","IT services"),305:("U",""),306:("T","Security Integrator (multi-line)"),
307:("U",""),308:("N","Consulting"),309:("U",""),310:("T","Access Control & Intercom"),
311:("N","Guard services"),312:("T","Fire & Life Safety"),313:("N","Guard services"),314:("U",""),
315:("T","Locksmith & Door Hardware"),316:("N","Guard services"),317:("T","Locksmith & Door Hardware"),
318:("N","Electrical contractor"),319:("T","Locksmith & Door Hardware"),320:("N","IT services"),
321:("N","Electrical contractor"),322:("N","Electrical contractor"),323:("T","Doors, Gates & Entrances"),
324:("T","Security Integrator (multi-line)"),325:("T","Security Integrator (multi-line)"),
326:("N","Guard services"),327:("N","Manufacturer"),328:("U",""),329:("U",""),330:("N","Electrical contractor"),
331:("U",""),332:("T","Alarm & Monitoring"),333:("D","Duplicate of Alarmco Systems / Securall"),
334:("N","Guard services"),335:("T","Alarm & Monitoring"),336:("T","Alarm & Monitoring"),
337:("N","Consulting"),338:("N","Manufacturer"),339:("U",""),340:("U",""),341:("N","IT services"),
342:("T","Locksmith & Door Hardware"),343:("N","Staffing / guard"),344:("U",""),
345:("A","Security products distributor"),346:("T","Fire & Life Safety"),347:("U",""),
348:("T","Fire & Life Safety"),349:("N","AI software"),350:("N","Distributor (Resideo)"),
351:("T","Alarm & Monitoring"),352:("T","Alarm & Monitoring"),353:("N","Finance"),354:("U",""),
355:("N","Guard / investigations"),356:("N","PE-owned (APi / Davis-Ulmer)"),357:("N","Consulting / guard"),
358:("N","Manufacturer"),359:("N","Guard services"),360:("T","Alarm & Monitoring"),
361:("T","Alarm & Monitoring"),362:("T","Alarm & Monitoring"),363:("N","Manufacturer"),
364:("N","Association"),365:("N","Car audio"),366:("N","Electrical contractor"),367:("N","Training"),
368:("N","IT / AV reseller"),369:("T","Alarm & Monitoring"),370:("T","Alarm & Monitoring"),
371:("N","Electrical contractor"),372:("T","Fire & Life Safety"),373:("T","Alarm & Monitoring"),
374:("T","Alarm & Monitoring"),375:("T","Security Integrator (multi-line)"),
376:("A","Plumbing contractor w/ sprinkler"),377:("N","AV"),378:("N","PE / strategic (Convergint)"),
379:("N","Electrical contractor"),380:("N","Guard services"),381:("T","Security Integrator (multi-line)"),
382:("N","Guard services"),383:("T","Alarm & Monitoring"),384:("N","Electrical contractor"),
385:("N","Electrical contractor"),386:("T","Security Integrator (multi-line)"),387:("U",""),
388:("N","Electrical contractor"),389:("N","Training"),390:("N","Distributor / bath & door supply"),
391:("T","Fire & Life Safety"),392:("U",""),393:("N","Electrical contractor"),394:("U",""),
395:("N","Windows"),396:("T","Doors, Gates & Entrances"),397:("T","Fire & Life Safety"),
398:("N","IT services"),399:("N","Manufacturer (lock maker)"),400:("T","Alarm & Monitoring"),
401:("N","Advisor"),402:("N","Guard services"),403:("N","Guard / consulting"),404:("T","Fire & Life Safety"),
405:("U",""),406:("N","Guard services"),407:("N","Electrical contractor"),408:("N","Electrical contractor"),
409:("N","Electrical contractor"),410:("N","Guard services"),411:("N","Electrical contractor"),
412:("A","ID products distributor"),413:("T","Security Integrator (multi-line)"),
414:("T","Security Integrator (multi-line)"),415:("N","IT services"),416:("N","Software"),
417:("N","Guard services"),418:("T","Security Integrator (multi-line)"),419:("N","Electrical contractor"),
420:("A","Door / hardware distributor"),421:("N","Distributor"),422:("T","Locksmith & Door Hardware"),
423:("N","Guard services"),424:("T","Locksmith & Door Hardware"),425:("T","Alarm & Monitoring"),
426:("T","Security Integrator (multi-line)"),427:("N","Electrical contractor"),428:("N","Electrical contractor"),
429:("N","Shower doors"),430:("N","Manufacturer"),431:("T","Fire & Life Safety"),
432:("N","Fence manufacturer/distributor; domain mismatch"),433:("U",""),434:("N","Electrical contractor"),
435:("N","Guard services"),436:("T","Fire & Life Safety"),437:("T","Fire & Life Safety"),438:("U",""),
439:("N","Guard services"),440:("N","Electrical contractor"),441:("N","Guard services"),
442:("T","Security Integrator (multi-line)"),443:("N","Training"),444:("N","Manufacturer"),
445:("T","Alarm & Monitoring"),446:("T","Alarm & Monitoring"),447:("N","Manufacturer"),
448:("T","Alarm & Monitoring"),449:("N","Furniture / retail"),450:("T","Security Integrator (multi-line)"),
451:("N","Manufacturer"),452:("N","Advisor"),453:("N","Electrical contractor"),454:("N","IT services"),
455:("N","Electrical contractor"),456:("T","Locksmith & Door Hardware"),457:("U",""),
458:("N","Investigations"),459:("N","EV charging"),460:("U",""),
461:("N","Electrical contractor"),462:("N","Bad domain match / duplicate of Rapid Response"),
463:("N","Software"),464:("T","Alarm & Monitoring"),465:("N","Manufacturer"),
466:("T","Doors, Gates & Entrances"),467:("N","Door distributor"),468:("A","Network cabling"),
469:("N","Training; domain mismatch"),470:("T","Doors, Gates & Entrances"),471:("N","Insurance / risk control"),
472:("N","Manufacturer"),473:("N","Electrical contractor"),474:("U",""),
475:("T","Security Integrator (multi-line)"),476:("U",""),477:("N","Broker / advisor tied to deal"),
478:("T","Alarm & Monitoring"),479:("N","Guard services"),480:("U",""),481:("N","Manufacturer"),
482:("N","Manufacturer"),483:("N","Guard services"),484:("N","Electrical contractor"),
485:("T","Fire & Life Safety"),486:("N","Electrical contractor"),487:("U",""),488:("U",""),
489:("N","Electrical contractor"),490:("N","Telecom"),491:("N","Broker / advisor tied to deal"),
492:("T","Alarm & Monitoring"),493:("U",""),494:("N","Electrical contractor"),495:("U",""),
496:("N","Advisor"),497:("T","Security Integrator (multi-line)"),498:("T","Doors, Gates & Entrances"),
499:("T","Doors, Gates & Entrances"),500:("N","Electrical contractor"),501:("T","Doors, Gates & Entrances"),
502:("T","Security Integrator (multi-line)"),503:("N","Cybersecurity"),504:("T","Alarm & Monitoring"),
505:("T","Alarm & Monitoring"),506:("A","Remote video guarding service"),507:("N","Electrical contractor"),
508:("N","ID / credential products"),509:("N","Manufacturer"),510:("N","Electrical contractor"),
511:("T","Fire & Life Safety"),512:("N","Guard services; domain mismatch"),513:("U",""),514:("N","Media"),
515:("T","Security Integrator (multi-line)"),516:("U",""),517:("T","Fire & Life Safety"),
518:("N","Guard services"),519:("T","Alarm & Monitoring"),520:("T","Locksmith & Door Hardware"),
521:("N","Electrical contractor"),522:("T","Alarm & Monitoring"),523:("T","Locksmith & Door Hardware"),
524:("U",""),525:("T","Doors, Gates & Entrances"),526:("U",""),527:("T","Alarm & Monitoring"),
528:("N","Electrical contractor"),529:("T","Alarm & Monitoring"),530:("N","Property services"),
531:("U",""),532:("A","Wholesale central station"),533:("T","Doors, Gates & Entrances"),
534:("D","Duplicate of Cypress Door & Glass"),535:("T","Security Integrator (multi-line)"),
536:("N","IT services"),537:("T","Locksmith & Door Hardware"),538:("T","Security Integrator (multi-line)"),
539:("T","Fire & Life Safety"),540:("N","Software"),541:("T","Alarm & Monitoring"),
542:("T","Alarm & Monitoring"),543:("T","Locksmith & Door Hardware"),544:("U",""),545:("N","Advisor"),
546:("T","Locksmith & Door Hardware"),547:("T","Security Integrator (multi-line)"),
548:("A","Hardware distributor"),549:("T","Security Integrator (multi-line)"),550:("T","Alarm & Monitoring"),
551:("N","Media"),552:("N","Software"),553:("T","Alarm & Monitoring"),554:("N","Consulting"),
555:("N","Advisor"),556:("T","Security Integrator (multi-line)"),557:("T","Security Integrator (multi-line)"),
558:("T","Alarm & Monitoring"),559:("U",""),560:("N","Distributor"),561:("T","Doors, Gates & Entrances"),
562:("U",""),563:("N","AV"),564:("T","Alarm & Monitoring"),565:("A","Fence contractor"),
566:("T","Alarm & Monitoring"),567:("N","Telecom / VoIP"),568:("T","Fire & Life Safety"),
569:("N","Guard services"),570:("N","Software"),571:("N","Electrical contractor"),572:("U",""),
573:("T","Alarm & Monitoring"),574:("T","Alarm & Monitoring"),575:("N","Software"),
576:("T","Security Integrator (multi-line)"),577:("N","Telecom"),578:("U",""),
579:("T","Security Integrator (multi-line)"),580:("T","Alarm & Monitoring"),
581:("T","Locksmith & Door Hardware"),582:("U",""),583:("U",""),584:("T","Fire & Life Safety"),
585:("N","University"),586:("N","Above buy-box"),587:("T","Alarm & Monitoring"),588:("U",""),
602:("N","Engineering firm"),603:("U",""),604:("T","Fire & Life Safety"),
605:("T","Locksmith & Door Hardware"),606:("T","Alarm & Monitoring"),607:("T","Alarm & Monitoring"),
608:("N","PE-owned (Permira)"),609:("T","Locksmith & Door Hardware"),610:("T","Video Surveillance"),
611:("T","Locksmith & Door Hardware"),612:("T","Alarm & Monitoring"),
613:("T","Access Control & Intercom"),614:("T","Security Integrator (multi-line)"),615:("U",""),
616:("T","Security Integrator (multi-line)"),617:("N","IT consulting"),618:("N","Manufacturer"),
619:("T","Security Integrator (multi-line)"),620:("N","Investment bank"),621:("N","Manufacturer"),
622:("U",""),623:("U",""),624:("N","IT services"),625:("N","Above buy-box / PE-backed"),
626:("N","Above buy-box"),627:("U",""),628:("N","PE-owned (Pavion)"),629:("N","Municipality"),
630:("N","Consulting"),631:("N","Advisor"),632:("T","Security Integrator (multi-line)"),
633:("U",""),634:("T","Alarm & Monitoring"),635:("U",""),
}
for i in range(589,602): S[i]=("N","Distributor (Wesco)")
