# domain: (zi_name, zi_industry, employees, revenue, city, state, parent, defunct)
Z = {
"srtechenterprise.com":(None,"NO_MATCH",None,None,"","",None,False),
"balfoursystems.com":("Balfour Systems","Repair Services",7,1351000,"Brooklyn","NY",None,False),
"esgny.com":("Enterprise Service Group","Repair Services",4,673000,"Brooklyn","NY",None,False),
"helltek.com":("HELLTEK","Security Products & Services",7,1156000,"Brooklyn","NY",None,False),
"irlsystems.com":("IRL Systems","Repair Services",20,5000000,"Brooklyn","NY",None,False),
"supercell.nyc":("Supercell Systems","Custom Software & IT Services",4,3046000,"Charlotte","NC",None,False),
"cktechnology.com":("CK Technology Group","Custom Software & IT Services",15,3758000,"New York","NY",None,False),
"lineartech.com":("Linear Technologies","Custom Software & IT Services",26,8394000,"New York","NY",None,False),
"mht-technologies.com":("MHT Technologies","Custom Software & IT Services",21,3432000,"New York","NY",None,False),
"ny360.net":(None,"NO_MATCH",None,None,"","",None,False),
"octeum.com":("Octeum","Custom Software & IT Services",25,5124000,"Fairport","NY",None,False),
"sbsnyc.com":("Signature Building Systems","Building Materials",18,6980000,"New York","NY",None,False),
"silverclassinc.com":("Silver Class","Rail, Bus & Taxi",7,1195000,"New York","NY",None,False),
"vamsglobal.com":("VAMS Global","Security Software",82,2564000,"New York","NY",None,False),
"absolutions.info":(None,"NO_MATCH",None,None,"","",None,False),
"eadv.com":("Eastern American Technologies","Commercial & Residential Construction",18,4313000,"Long Island City","NY",None,False),
"gridsquared.com":("Grid Squared Systems","Custom Software & IT Services",12,1000000,"Astoria","NY",None,False),
"kiskasolutions.com":("Kiska Solutions","Commercial & Residential Construction",24,5000000,"Flushing","NY",None,False),
"madisonservice.com":("Madison Service","Repair Services",15,3450000,"Bayside","NY",None,False),
"netfoxsolutions.com":("NETFOX Solutions","Custom Software & IT Services",9,1163000,"Woodside","NY",None,False),
"blackhawkli.com":("BlackHawk","Commercial & Residential Construction",2,515000,"Patchogue","NY",None,False),
"brookhillny.com":(None,"NO_MATCH",None,None,"","",None,False),
"classicsystemsinc.com":("Classic Systems","Commercial & Residential Construction",24,3783000,"Westbury","NY",None,False),
"nattechinc.com":("National Technology Group","Custom Software & IT Services",69,7613000,"Holbrook","NY",None,False),
"activatedsystemsinc.com":("Activated Systems","Security Products & Services",5,899000,"Franklin Square","NY",None,False),
"arssyscorp.com":("ARS Systems","Colleges & Universities",11,2382000,"Elmont","NY",None,False),
"edgenet.biz":("Edgenet Services","Custom Software & IT Services",5,1146000,"Great Neck","NY",None,False),
"goodstrong.com":("Goodstrong Lock & Alarm","Security Products & Services",19,4644000,"New Hyde Park","NY",None,True),
"latechgroup.com":("LA Technology Group","Custom Software & IT Services",7,1164000,"Freeport","NY",None,False),
"rapidmotiontechnology.com":("Rapid Motion Technology","Commercial & Residential Construction",15,3413000,"Westbury","NY",None,False),
"sastechnologies.com":("SAS Technologies","Security Products & Services",14,4300000,"Lynbrook","NY",None,False),
"shoresys.com":("Shore Systems","Security Products & Services",9,1845000,"Roslyn Heights","NY","Perimeter Security Partners LLC",False),
"sptcorp.net":("SPT","Electricity, Oil & Gas",15,3274000,"New York","NY",None,False),
"everydaytechservices-llc.com":("Everyday Technology Services","Custom Software & IT Services",16,4513000,"","",None,False),
"functionalsystems.com":("Functional Systems","Commercial & Residential Construction",8,970000,"Dix Hills","NY",None,False),
"keysignals.com":("Key Signals","Repair Services",6,1144000,"East Moriches","NY",None,False),
"macrodigital.com":("Macro Digital Technology","Custom Software & IT Services",8,1561000,"Bohemia","NY",None,False),
"majesticsystems.com":("Majestic System","Building Materials",6,1011000,"East Northport","NY",None,False),
"techforcetfi.com":("Tech Force","Custom Software & IT Services",10,1553000,"Babylon","NY",None,False),
"powertbs.com":("Power Tech Business Solutions","Electricity, Oil & Gas",25,3341000,"Monroe","NY",None,False),
"dtminstallations.com":("DTM Installations","Repair Services",12,2570000,"Garnerville","NY",None,False),
"fessolution.com":("Falcon Engineered Security Solutions","Commercial & Residential Construction",11,5804000,"Yonkers","NY",None,False),
"matrixtg.com":("Matrix Technology Group","Custom Software & IT Services",387,20721000,"Long Island City","NY",None,False),
"msselectronics.com":("MSS Electronics","Security Products & Services",20,4290000,"White Plains","NY",None,False),
"roloelectronics.com":("ROLO Electronics","Electricity, Oil & Gas",17,3281000,"Rye","NY",None,False),
"rzssolutions.com":("RZS Solutions","Commercial & Residential Construction",8,864000,"Hawthorne","NY",None,False),
"aas-tech.com":("AAS Technologies","Security Products & Services",15,5030000,"Hackensack","NJ",None,False),
"enterprisecc.com":(None,"NO_MATCH",None,None,"","",None,False),
"fcsmetro.com":("FCS Metro","Security Products & Services",17,5131000,"Jersey City","NJ",None,False),
"powertechna.com":("Power Technology","Telecommunication Equipment",7,2213000,"Hackensack","NJ",None,False),
"premierconnectinc.com":("Premier Connect","Custom Software & IT Services",14,3885000,"Englewood Cliffs","NJ",None,False),
"tecsolutionsinc.com":("Tec Solutions","Custom Software & IT Services",11,4897000,"Hoboken","NJ",None,False),
"topsystemsinc.com":("Top Systems","Commercial & Residential Construction",11,1379000,"Flushing","NY",None,False),
"vkcsystems.com":("VKC Systems","Custom Software & IT Services",11,5000000,"South Hackensack","NJ",None,False),
"gmiautomation.com":("GMI Automation","Custom Software & IT Services",97,19577000,"Old Bridge","NJ",None,False),
"seamlesstechnologies.net":("Seamless Technologies","Custom Software & IT Services",12,1327000,"Clifton","NJ",None,False),
"peloda.com":("Peloda Systems","Custom Software & IT Services",16,500000,"Avenel","NJ",None,False),
"rightech.net":("Rightech","HR & Staffing",225,65695000,"Iselin","NJ",None,False),
"techservicesnj.com":("Tech Services of New Jersey","Security Products & Services",15,3518000,"South Plainfield","NJ",None,False),
"eastec.com":("Eastec","Security Products & Services",33,4574000,"Neptune City","NJ",None,False),
"wickedtechnologies.com":("Wicked Technologies","Custom Software & IT Services",3,461000,"Lincoln Park","NJ",None,False),
"apscorporation.com":("APS","Security Products & Services",9,3232000,"Branchburg","NJ","Pye Barker Fire & Safety",False),
"the700nano.com":("700 Nano","Commercial & Residential Construction",3,1368000,"Linden","NJ",None,False),
"jctnj.com":("JCT Solutions","Custom Software & IT Services",72,12239000,"Springfield","NJ",None,False),
"newworldsolutions.com":("New World Solutions","Repair Services",7,1605000,"Elizabeth","NJ",None,False),
}
